# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premier_team_lite_response_data import PremierTeamLiteResponseData

class TestPremierTeamLiteResponseData(unittest.TestCase):
    """PremierTeamLiteResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremierTeamLiteResponseData:
        """Test PremierTeamLiteResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremierTeamLiteResponseData`
        """
        model = PremierTeamLiteResponseData()
        if include_optional:
            return PremierTeamLiteResponseData(
                affinity = '',
                conference = '',
                customization = henrikdev_api_client.models.premier_team_v1_response_data_customization.PremierTeamV1ResponseDataCustomization(
                    icon = '', 
                    image = '', 
                    primary = '', 
                    secondary = '', 
                    tertiary = '', ),
                division = 56,
                id = '',
                losses = 56,
                name = '',
                ranked = True,
                ranking = 56,
                region = '',
                score = 56,
                tag = '',
                updated_at = '',
                wins = 56
            )
        else:
            return PremierTeamLiteResponseData(
                affinity = '',
                conference = '',
                customization = henrikdev_api_client.models.premier_team_v1_response_data_customization.PremierTeamV1ResponseDataCustomization(
                    icon = '', 
                    image = '', 
                    primary = '', 
                    secondary = '', 
                    tertiary = '', ),
                division = 56,
                id = '',
                losses = 56,
                name = '',
                ranked = True,
                ranking = 56,
                region = '',
                score = 56,
                tag = '',
                updated_at = '',
                wins = 56,
        )
        """

    def testPremierTeamLiteResponseData(self):
        """Test PremierTeamLiteResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
