# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.api.premium_api import PremiumApi


class TestPremiumApi(unittest.TestCase):
    """PremiumApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PremiumApi()

    def tearDown(self) -> None:
        pass

    def test_add_webhook_user(self) -> None:
        """Test case for add_webhook_user

        Add premium webhook user
        """
        pass

    def test_delete_webhook_user(self) -> None:
        """Test case for delete_webhook_user

        Delete premium webhook user
        """
        pass

    def test_get_webhook_settings(self) -> None:
        """Test case for get_webhook_settings

        Get premium webhook settings
        """
        pass

    def test_update_webhook_user(self) -> None:
        """Test case for update_webhook_user

        Update premium webhook user
        """
        pass


if __name__ == '__main__':
    unittest.main()
