# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premium_webhook_user_mutation_response import PremiumWebhookUserMutationResponse

class TestPremiumWebhookUserMutationResponse(unittest.TestCase):
    """PremiumWebhookUserMutationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremiumWebhookUserMutationResponse:
        """Test PremiumWebhookUserMutationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremiumWebhookUserMutationResponse`
        """
        model = PremiumWebhookUserMutationResponse()
        if include_optional:
            return PremiumWebhookUserMutationResponse(
                data = henrikdev_api_client.models.premium_webhook_user_mutation_data.PremiumWebhookUserMutationData(
                    success = True, 
                    user = henrikdev_api_client.models.premium_webhook_user_response.PremiumWebhookUserResponse(
                        created_at = 56, 
                        enabled = True, 
                        events = [
                            'MATCH'
                            ], 
                        id = '', 
                        last_checked_at = 56, 
                        last_match = '', 
                        last_mmr = 56, 
                        puuid = '', 
                        region = '', 
                        updated_at = 56, ), )
            )
        else:
            return PremiumWebhookUserMutationResponse(
                data = henrikdev_api_client.models.premium_webhook_user_mutation_data.PremiumWebhookUserMutationData(
                    success = True, 
                    user = henrikdev_api_client.models.premium_webhook_user_response.PremiumWebhookUserResponse(
                        created_at = 56, 
                        enabled = True, 
                        events = [
                            'MATCH'
                            ], 
                        id = '', 
                        last_checked_at = 56, 
                        last_match = '', 
                        last_mmr = 56, 
                        puuid = '', 
                        region = '', 
                        updated_at = 56, ), ),
        )
        """

    def testPremiumWebhookUserMutationResponse(self):
        """Test PremiumWebhookUserMutationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
