/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.apis.PremiumApi
import henrikdevApiClient.models.PremiumWebhookDeleteResponse
import henrikdevApiClient.models.PremiumWebhookUserAddRequest
import henrikdevApiClient.models.PremiumWebhookUserMutationResponse
import henrikdevApiClient.models.PremiumWebhookUserUpdateRequest
import henrikdevApiClient.models.SendError

class PremiumApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremiumApi
        //val apiInstance = PremiumApi()

        // to test addWebhookUser
        should("test addWebhookUser") {
            // uncomment below to test addWebhookUser
            //val premiumWebhookUserAddRequest : PremiumWebhookUserAddRequest =  // PremiumWebhookUserAddRequest | 
            //val result : PremiumWebhookUserMutationResponse = apiInstance.addWebhookUser(premiumWebhookUserAddRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteWebhookUser
        should("test deleteWebhookUser") {
            // uncomment below to test deleteWebhookUser
            //val id : kotlin.String = id_example // kotlin.String | Tracked user id
            //val result : PremiumWebhookDeleteResponse = apiInstance.deleteWebhookUser(id)
            //result shouldBe ("TODO")
        }

        // to test getWebhookSettings
        should("test getWebhookSettings") {
            // uncomment below to test getWebhookSettings
            //apiInstance.getWebhookSettings()
        }

        // to test updateWebhookUser
        should("test updateWebhookUser") {
            // uncomment below to test updateWebhookUser
            //val id : kotlin.String = id_example // kotlin.String | Tracked user id
            //val premiumWebhookUserUpdateRequest : PremiumWebhookUserUpdateRequest =  // PremiumWebhookUserUpdateRequest | 
            //apiInstance.updateWebhookUser(id, premiumWebhookUserUpdateRequest)
        }

    }
}
