/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.PremiumWebhookUserAddRequest
import henrikdevApiClient.models.PremiumWebhookEvent

class PremiumWebhookUserAddRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremiumWebhookUserAddRequest
        //val modelInstance = PremiumWebhookUserAddRequest()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `puuid`
        should("test puuid") {
            // uncomment below to test the property
            //modelInstance.puuid shouldBe ("TODO")
        }

        // to test the property `tag`
        should("test tag") {
            // uncomment below to test the property
            //modelInstance.tag shouldBe ("TODO")
        }

    }
}
