<?php
/**
 * ValorantApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ValorantApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ValorantApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for crosshair
     *
     * Generate crosshair image (v1).
     *
     */
    public function testCrosshair()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsEventV2
     *
     * Get VLR event matches (v2).
     *
     */
    public function testEsportsEventV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsEventsV2
     *
     * Get VLR esports events (v2).
     *
     */
    public function testEsportsEventsV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsMatchV2
     *
     * Get VLR match details (v2).
     *
     */
    public function testEsportsMatchV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsPlayerMatchesV2
     *
     * Get VLR player matches (v2).
     *
     */
    public function testEsportsPlayerMatchesV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsPlayerV2
     *
     * Get VLR player (v2).
     *
     */
    public function testEsportsPlayerV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsSchedulesV1
     *
     * Get esports schedule (v1).
     *
     */
    public function testEsportsSchedulesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsTeamMatchesV2
     *
     * Get VLR team matches (v2).
     *
     */
    public function testEsportsTeamMatchesV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsTeamTransactionsV2
     *
     * Get VLR team transactions (v2).
     *
     */
    public function testEsportsTeamTransactionsV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for esportsTeamV2
     *
     * Get VLR team (v2).
     *
     */
    public function testEsportsTeamV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountByIdV1
     *
     * Get account by PUUID (v1).
     *
     */
    public function testGetAccountByIdV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountByIdV2
     *
     * Get account by PUUID (v2).
     *
     */
    public function testGetAccountByIdV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountV1
     *
     * Get account (v1).
     *
     */
    public function testGetAccountV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountV2
     *
     * Get account (v2).
     *
     */
    public function testGetAccountV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContentV1
     *
     * Get content (v1).
     *
     */
    public function testGetContentV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMatchesV3ById
     *
     * Get matches by PUUID (v3).
     *
     */
    public function testGetMatchesV3ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMatchesV3ByName
     *
     * Get matches by name (v3).
     *
     */
    public function testGetMatchesV3ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMatchesV4ById
     *
     * Get matches by PUUID (v4).
     *
     */
    public function testGetMatchesV4ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMatchesV4ByName
     *
     * Get matches by name (v4).
     *
     */
    public function testGetMatchesV4ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrHistoryById
     *
     * Get MMR history by PUUID (v1).
     *
     */
    public function testGetMmrHistoryById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrHistoryByName
     *
     * Get MMR history by name (v1).
     *
     */
    public function testGetMmrHistoryByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrHistoryV2ById
     *
     * Get MMR history by PUUID (v2).
     *
     */
    public function testGetMmrHistoryV2ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrHistoryV2ByName
     *
     * Get MMR history by name (v2).
     *
     */
    public function testGetMmrHistoryV2ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV1ById
     *
     * Get MMR by PUUID (v1).
     *
     */
    public function testGetMmrV1ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV1ByName
     *
     * Get MMR by name (v1).
     *
     */
    public function testGetMmrV1ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV2ById
     *
     * Get MMR by PUUID (v2).
     *
     */
    public function testGetMmrV2ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV2ByName
     *
     * Get MMR by name (v2).
     *
     */
    public function testGetMmrV2ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV3ById
     *
     * Get MMR by PUUID (v3).
     *
     */
    public function testGetMmrV3ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMmrV3ByName
     *
     * Get MMR by name (v3).
     *
     */
    public function testGetMmrV3ByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for leaderboardV1
     *
     * Get leaderboard (v1).
     *
     */
    public function testLeaderboardV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for leaderboardV2
     *
     * Get leaderboard (v2).
     *
     */
    public function testLeaderboardV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for leaderboardV3
     *
     * Get leaderboard (v3).
     *
     */
    public function testLeaderboardV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for matchV2
     *
     * Get match details (v2).
     *
     */
    public function testMatchV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for matchV4
     *
     * Get match details (v4).
     *
     */
    public function testMatchV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierById
     *
     * Get Premier team by ID (v1).
     *
     */
    public function testPremierById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierByIdHistory
     *
     * Get Premier team history by ID (v1).
     *
     */
    public function testPremierByIdHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierByName
     *
     * Get Premier team by name (v1).
     *
     */
    public function testPremierByName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierByNameHistory
     *
     * Get Premier team history by name (v1).
     *
     */
    public function testPremierByNameHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierLeaderboard
     *
     * Get Premier leaderboard (v1).
     *
     */
    public function testPremierLeaderboard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for premierSearch
     *
     * Search Premier teams (v1).
     *
     */
    public function testPremierSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queueStatus
     *
     * Get queue status (v1).
     *
     */
    public function testQueueStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for raw
     *
     * Get raw Riot API data (v1).
     *
     */
    public function testRaw()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for status
     *
     * Get status (v1).
     *
     */
    public function testStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeFeatured
     *
     * Get featured store items.
     *
     */
    public function testStoreFeatured()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeOffers
     *
     * Get store offers.
     *
     */
    public function testStoreOffers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMatches
     *
     * Get stored matches by name (v1).
     *
     */
    public function testStoredMatches()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMatchesById
     *
     * Get stored matches by PUUID (v1).
     *
     */
    public function testStoredMatchesById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMmrHistory
     *
     * Get stored MMR history by name (v1).
     *
     */
    public function testStoredMmrHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMmrHistoryById
     *
     * Get stored MMR history by PUUID (v1).
     *
     */
    public function testStoredMmrHistoryById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMmrHistoryV2
     *
     * Get stored MMR history by name (v2).
     *
     */
    public function testStoredMmrHistoryV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storedMmrHistoryV2ById
     *
     * Get stored MMR history by PUUID (v2).
     *
     */
    public function testStoredMmrHistoryV2ById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for version
     *
     * Get game version (v1).
     *
     */
    public function testVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for website
     *
     * Get website content (v1).
     *
     */
    public function testWebsite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for websiteById
     *
     * Get website entry by ID (v1).
     *
     */
    public function testWebsiteById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
