/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import henrikdevApiClient.models.PremiumWebhookDeleteResponse
import henrikdevApiClient.models.PremiumWebhookUserAddRequest
import henrikdevApiClient.models.PremiumWebhookUserMutationResponse
import henrikdevApiClient.models.PremiumWebhookUserUpdateRequest
import henrikdevApiClient.models.SendError

import com.squareup.moshi.Json

import henrikdevApiClient.infrastructure.ApiClient
import henrikdevApiClient.infrastructure.ApiResponse
import henrikdevApiClient.infrastructure.ClientException
import henrikdevApiClient.infrastructure.ClientError
import henrikdevApiClient.infrastructure.ServerException
import henrikdevApiClient.infrastructure.ServerError
import henrikdevApiClient.infrastructure.MultiValueMap
import henrikdevApiClient.infrastructure.PartConfig
import henrikdevApiClient.infrastructure.RequestConfig
import henrikdevApiClient.infrastructure.RequestMethod
import henrikdevApiClient.infrastructure.ResponseType
import henrikdevApiClient.infrastructure.Success
import henrikdevApiClient.infrastructure.toMultiValue

open class PremiumApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.henrikdev.xyz")
        }
    }

    /**
     * POST /public/v1/premium/webhook/users
     * Add premium webhook user
     * 
     * @param premiumWebhookUserAddRequest 
     * @return PremiumWebhookUserMutationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun addWebhookUser(premiumWebhookUserAddRequest: PremiumWebhookUserAddRequest) : PremiumWebhookUserMutationResponse {
        val localVarResponse = addWebhookUserWithHttpInfo(premiumWebhookUserAddRequest = premiumWebhookUserAddRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PremiumWebhookUserMutationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /public/v1/premium/webhook/users
     * Add premium webhook user
     * 
     * @param premiumWebhookUserAddRequest 
     * @return ApiResponse<PremiumWebhookUserMutationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun addWebhookUserWithHttpInfo(premiumWebhookUserAddRequest: PremiumWebhookUserAddRequest) : ApiResponse<PremiumWebhookUserMutationResponse?> {
        val localVariableConfig = addWebhookUserRequestConfig(premiumWebhookUserAddRequest = premiumWebhookUserAddRequest)

        return request<PremiumWebhookUserAddRequest, PremiumWebhookUserMutationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation addWebhookUser
     *
     * @param premiumWebhookUserAddRequest 
     * @return RequestConfig
     */
    fun addWebhookUserRequestConfig(premiumWebhookUserAddRequest: PremiumWebhookUserAddRequest) : RequestConfig<PremiumWebhookUserAddRequest> {
        val localVariableBody = premiumWebhookUserAddRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/public/v1/premium/webhook/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /public/v1/premium/webhook/users/{id}
     * Delete premium webhook user
     * 
     * @param id Tracked user id
     * @return PremiumWebhookDeleteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteWebhookUser(id: kotlin.String) : PremiumWebhookDeleteResponse {
        val localVarResponse = deleteWebhookUserWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PremiumWebhookDeleteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /public/v1/premium/webhook/users/{id}
     * Delete premium webhook user
     * 
     * @param id Tracked user id
     * @return ApiResponse<PremiumWebhookDeleteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteWebhookUserWithHttpInfo(id: kotlin.String) : ApiResponse<PremiumWebhookDeleteResponse?> {
        val localVariableConfig = deleteWebhookUserRequestConfig(id = id)

        return request<Unit, PremiumWebhookDeleteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteWebhookUser
     *
     * @param id Tracked user id
     * @return RequestConfig
     */
    fun deleteWebhookUserRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/public/v1/premium/webhook/users/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /public/v1/premium/webhook
     * Get premium webhook settings
     * 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getWebhookSettings() : Unit {
        val localVarResponse = getWebhookSettingsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /public/v1/premium/webhook
     * Get premium webhook settings
     * 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun getWebhookSettingsWithHttpInfo() : ApiResponse<Unit?> {
        val localVariableConfig = getWebhookSettingsRequestConfig()

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWebhookSettings
     *
     * @return RequestConfig
     */
    fun getWebhookSettingsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/public/v1/premium/webhook",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /public/v1/premium/webhook/users/{id}
     * Update premium webhook user
     * 
     * @param id Tracked user id
     * @param premiumWebhookUserUpdateRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateWebhookUser(id: kotlin.String, premiumWebhookUserUpdateRequest: PremiumWebhookUserUpdateRequest) : Unit {
        val localVarResponse = updateWebhookUserWithHttpInfo(id = id, premiumWebhookUserUpdateRequest = premiumWebhookUserUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /public/v1/premium/webhook/users/{id}
     * Update premium webhook user
     * 
     * @param id Tracked user id
     * @param premiumWebhookUserUpdateRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun updateWebhookUserWithHttpInfo(id: kotlin.String, premiumWebhookUserUpdateRequest: PremiumWebhookUserUpdateRequest) : ApiResponse<Unit?> {
        val localVariableConfig = updateWebhookUserRequestConfig(id = id, premiumWebhookUserUpdateRequest = premiumWebhookUserUpdateRequest)

        return request<PremiumWebhookUserUpdateRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateWebhookUser
     *
     * @param id Tracked user id
     * @param premiumWebhookUserUpdateRequest 
     * @return RequestConfig
     */
    fun updateWebhookUserRequestConfig(id: kotlin.String, premiumWebhookUserUpdateRequest: PremiumWebhookUserUpdateRequest) : RequestConfig<PremiumWebhookUserUpdateRequest> {
        val localVariableBody = premiumWebhookUserUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/public/v1/premium/webhook/users/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
