# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from henrikdev_api_client.models.bundle_item import BundleItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Bundle(BaseModel):
    """
    Bundle
    """ # noqa: E501
    currency_id: StrictStr = Field(alias="CurrencyID")
    data_asset_id: StrictStr = Field(alias="DataAssetID")
    duration_remaining_in_seconds: Annotated[int, Field(strict=True, ge=0)] = Field(alias="DurationRemainingInSeconds")
    id: StrictStr = Field(alias="ID")
    items: List[BundleItem] = Field(alias="Items")
    total_discount_percent: Union[StrictFloat, StrictInt] = Field(alias="TotalDiscountPercent")
    wholesale_only: StrictBool = Field(alias="WholesaleOnly")
    __properties: ClassVar[List[str]] = ["CurrencyID", "DataAssetID", "DurationRemainingInSeconds", "ID", "Items", "TotalDiscountPercent", "WholesaleOnly"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Bundle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                _items.append(_item_items.to_dict() if _item_items is not None else None)
            _dict['Items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Bundle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CurrencyID": obj.get("CurrencyID"),
            "DataAssetID": obj.get("DataAssetID"),
            "DurationRemainingInSeconds": obj.get("DurationRemainingInSeconds"),
            "ID": obj.get("ID"),
            "Items": [BundleItem.from_dict(_item) for _item in obj["Items"]] if obj.get("Items") is not None else None,
            "TotalDiscountPercent": obj.get("TotalDiscountPercent"),
            "WholesaleOnly": obj.get("WholesaleOnly")
        })
        return _obj


