# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from henrikdev_api_client.models.esports_v2_id_slug import EsportsV2IdSlug
from henrikdev_api_client.models.esports_v2_match_league import EsportsV2MatchLeague
from henrikdev_api_client.models.esports_v2_team_match_team import EsportsV2TeamMatchTeam
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EsportsV2TeamMatch(BaseModel):
    """
    EsportsV2TeamMatch
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    league: EsportsV2MatchLeague
    match: EsportsV2IdSlug
    teams: List[EsportsV2TeamMatchTeam]
    vods: List[StrictStr]
    __properties: ClassVar[List[str]] = ["date", "league", "match", "teams", "vods"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsportsV2TeamMatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of league
        if self.league:
            _dict['league'] = self.league.to_dict()
        # override the default output from pydantic by calling `to_dict()` of match
        if self.match:
            _dict['match'] = self.match.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in teams (list)
        _items = []
        if self.teams:
            for _item_teams in self.teams:
                _items.append(_item_teams.to_dict() if _item_teams is not None else None)
            _dict['teams'] = _items
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsportsV2TeamMatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "league": EsportsV2MatchLeague.from_dict(obj["league"]) if obj.get("league") is not None else None,
            "match": EsportsV2IdSlug.from_dict(obj["match"]) if obj.get("match") is not None else None,
            "teams": [EsportsV2TeamMatchTeam.from_dict(_item) for _item in obj["teams"]] if obj.get("teams") is not None else None,
            "vods": obj.get("vods")
        })
        return _obj


