# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from henrikdev_api_client.models.esports_v2_match_game_player import EsportsV2MatchGamePlayer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EsportsV2MatchGameTeam(BaseModel):
    """
    EsportsV2MatchGameTeam
    """ # noqa: E501
    is_winner: StrictBool
    name: StrictStr
    players: List[EsportsV2MatchGamePlayer]
    score: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    score_ct: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    score_t: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["is_winner", "name", "players", "score", "score_ct", "score_t"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsportsV2MatchGameTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in players (list)
        _items = []
        if self.players:
            for _item_players in self.players:
                _items.append(_item_players.to_dict() if _item_players is not None else None)
            _dict['players'] = _items
        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if score_ct (nullable) is None
        # and model_fields_set contains the field
        if self.score_ct is None and "score_ct" in self.model_fields_set:
            _dict['score_ct'] = None

        # set to None if score_t (nullable) is None
        # and model_fields_set contains the field
        if self.score_t is None and "score_t" in self.model_fields_set:
            _dict['score_t'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsportsV2MatchGameTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_winner": obj.get("is_winner"),
            "name": obj.get("name"),
            "players": [EsportsV2MatchGamePlayer.from_dict(_item) for _item in obj["players"]] if obj.get("players") is not None else None,
            "score": obj.get("score"),
            "score_ct": obj.get("score_ct"),
            "score_t": obj.get("score_t")
        })
        return _obj


