# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from henrikdev_api_client.models.esports_v2_head_to_head_match import EsportsV2HeadToHeadMatch
from henrikdev_api_client.models.esports_v2_match_economy import EsportsV2MatchEconomy
from henrikdev_api_client.models.esports_v2_match_game import EsportsV2MatchGame
from henrikdev_api_client.models.esports_v2_match_header import EsportsV2MatchHeader
from henrikdev_api_client.models.esports_v2_match_header_team import EsportsV2MatchHeaderTeam
from henrikdev_api_client.models.esports_v2_match_performance import EsportsV2MatchPerformance
from henrikdev_api_client.models.esports_v2_match_stream import EsportsV2MatchStream
from henrikdev_api_client.models.esports_v2_team_past_matches import EsportsV2TeamPastMatches
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EsportsV2Match(BaseModel):
    """
    EsportsV2Match
    """ # noqa: E501
    economy: Optional[EsportsV2MatchEconomy] = None
    games: List[EsportsV2MatchGame]
    head_to_head: List[EsportsV2HeadToHeadMatch]
    metadata: EsportsV2MatchHeader
    past_matches: List[EsportsV2TeamPastMatches]
    performance: Optional[EsportsV2MatchPerformance] = None
    streams: List[EsportsV2MatchStream]
    teams: List[EsportsV2MatchHeaderTeam]
    vods: List[EsportsV2MatchStream]
    __properties: ClassVar[List[str]] = ["economy", "games", "head_to_head", "metadata", "past_matches", "performance", "streams", "teams", "vods"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsportsV2Match from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of economy
        if self.economy:
            _dict['economy'] = self.economy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in games (list)
        _items = []
        if self.games:
            for _item_games in self.games:
                _items.append(_item_games.to_dict() if _item_games is not None else None)
            _dict['games'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in head_to_head (list)
        _items = []
        if self.head_to_head:
            for _item_head_to_head in self.head_to_head:
                _items.append(_item_head_to_head.to_dict() if _item_head_to_head is not None else None)
            _dict['head_to_head'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in past_matches (list)
        _items = []
        if self.past_matches:
            for _item_past_matches in self.past_matches:
                _items.append(_item_past_matches.to_dict() if _item_past_matches is not None else None)
            _dict['past_matches'] = _items
        # override the default output from pydantic by calling `to_dict()` of performance
        if self.performance:
            _dict['performance'] = self.performance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in streams (list)
        _items = []
        if self.streams:
            for _item_streams in self.streams:
                _items.append(_item_streams.to_dict() if _item_streams is not None else None)
            _dict['streams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in teams (list)
        _items = []
        if self.teams:
            for _item_teams in self.teams:
                _items.append(_item_teams.to_dict() if _item_teams is not None else None)
            _dict['teams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in vods (list)
        _items = []
        if self.vods:
            for _item_vods in self.vods:
                _items.append(_item_vods.to_dict() if _item_vods is not None else None)
            _dict['vods'] = _items
        # set to None if economy (nullable) is None
        # and model_fields_set contains the field
        if self.economy is None and "economy" in self.model_fields_set:
            _dict['economy'] = None

        # set to None if performance (nullable) is None
        # and model_fields_set contains the field
        if self.performance is None and "performance" in self.model_fields_set:
            _dict['performance'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsportsV2Match from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "economy": EsportsV2MatchEconomy.from_dict(obj["economy"]) if obj.get("economy") is not None else None,
            "games": [EsportsV2MatchGame.from_dict(_item) for _item in obj["games"]] if obj.get("games") is not None else None,
            "head_to_head": [EsportsV2HeadToHeadMatch.from_dict(_item) for _item in obj["head_to_head"]] if obj.get("head_to_head") is not None else None,
            "metadata": EsportsV2MatchHeader.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "past_matches": [EsportsV2TeamPastMatches.from_dict(_item) for _item in obj["past_matches"]] if obj.get("past_matches") is not None else None,
            "performance": EsportsV2MatchPerformance.from_dict(obj["performance"]) if obj.get("performance") is not None else None,
            "streams": [EsportsV2MatchStream.from_dict(_item) for _item in obj["streams"]] if obj.get("streams") is not None else None,
            "teams": [EsportsV2MatchHeaderTeam.from_dict(_item) for _item in obj["teams"]] if obj.get("teams") is not None else None,
            "vods": [EsportsV2MatchStream.from_dict(_item) for _item in obj["vods"]] if obj.get("vods") is not None else None
        })
        return _obj


