# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from henrikdev_api_client.models.esports_v2_country import EsportsV2Country
from henrikdev_api_client.models.esports_v2_event_placement import EsportsV2EventPlacement
from henrikdev_api_client.models.esports_v2_player_agent_stats import EsportsV2PlayerAgentStats
from henrikdev_api_client.models.esports_v2_player_team import EsportsV2PlayerTeam
from henrikdev_api_client.models.esports_v2_social import EsportsV2Social
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EsportsV2Player(BaseModel):
    """
    EsportsV2Player
    """ # noqa: E501
    agent_stats: List[EsportsV2PlayerAgentStats]
    avatar: Optional[StrictStr] = None
    country: Optional[EsportsV2Country] = None
    current_teams: List[EsportsV2PlayerTeam]
    event_placements: List[EsportsV2EventPlacement]
    id: Annotated[int, Field(strict=True, ge=0)]
    name: StrictStr
    past_teams: List[EsportsV2PlayerTeam]
    real_name: Optional[StrictStr] = None
    socials: List[EsportsV2Social]
    total_winnings: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["agent_stats", "avatar", "country", "current_teams", "event_placements", "id", "name", "past_teams", "real_name", "socials", "total_winnings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsportsV2Player from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in agent_stats (list)
        _items = []
        if self.agent_stats:
            for _item_agent_stats in self.agent_stats:
                _items.append(_item_agent_stats.to_dict() if _item_agent_stats is not None else None)
            _dict['agent_stats'] = _items
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict['country'] = self.country.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in current_teams (list)
        _items = []
        if self.current_teams:
            for _item_current_teams in self.current_teams:
                _items.append(_item_current_teams.to_dict() if _item_current_teams is not None else None)
            _dict['current_teams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in event_placements (list)
        _items = []
        if self.event_placements:
            for _item_event_placements in self.event_placements:
                _items.append(_item_event_placements.to_dict() if _item_event_placements is not None else None)
            _dict['event_placements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in past_teams (list)
        _items = []
        if self.past_teams:
            for _item_past_teams in self.past_teams:
                _items.append(_item_past_teams.to_dict() if _item_past_teams is not None else None)
            _dict['past_teams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in socials (list)
        _items = []
        if self.socials:
            for _item_socials in self.socials:
                _items.append(_item_socials.to_dict() if _item_socials is not None else None)
            _dict['socials'] = _items
        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict['avatar'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if real_name (nullable) is None
        # and model_fields_set contains the field
        if self.real_name is None and "real_name" in self.model_fields_set:
            _dict['real_name'] = None

        # set to None if total_winnings (nullable) is None
        # and model_fields_set contains the field
        if self.total_winnings is None and "total_winnings" in self.model_fields_set:
            _dict['total_winnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsportsV2Player from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_stats": [EsportsV2PlayerAgentStats.from_dict(_item) for _item in obj["agent_stats"]] if obj.get("agent_stats") is not None else None,
            "avatar": obj.get("avatar"),
            "country": EsportsV2Country.from_dict(obj["country"]) if obj.get("country") is not None else None,
            "current_teams": [EsportsV2PlayerTeam.from_dict(_item) for _item in obj["current_teams"]] if obj.get("current_teams") is not None else None,
            "event_placements": [EsportsV2EventPlacement.from_dict(_item) for _item in obj["event_placements"]] if obj.get("event_placements") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "past_teams": [EsportsV2PlayerTeam.from_dict(_item) for _item in obj["past_teams"]] if obj.get("past_teams") is not None else None,
            "real_name": obj.get("real_name"),
            "socials": [EsportsV2Social.from_dict(_item) for _item in obj["socials"]] if obj.get("socials") is not None else None,
            "total_winnings": obj.get("total_winnings")
        })
        return _obj


