# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from henrikdev_api_client.models.esports_v2_country import EsportsV2Country
from henrikdev_api_client.models.esports_v2_event_placement import EsportsV2EventPlacement
from henrikdev_api_client.models.esports_v2_social import EsportsV2Social
from henrikdev_api_client.models.esports_v2_team_roster_member import EsportsV2TeamRosterMember
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EsportsV2Team(BaseModel):
    """
    EsportsV2Team
    """ # noqa: E501
    country: Optional[EsportsV2Country] = None
    event_placements: List[EsportsV2EventPlacement]
    id: Annotated[int, Field(strict=True, ge=0)]
    logo: Optional[StrictStr] = None
    name: StrictStr
    roster: List[EsportsV2TeamRosterMember]
    socials: List[EsportsV2Social]
    tag: Optional[StrictStr] = None
    total_winnings: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["country", "event_placements", "id", "logo", "name", "roster", "socials", "tag", "total_winnings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsportsV2Team from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict['country'] = self.country.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in event_placements (list)
        _items = []
        if self.event_placements:
            for _item_event_placements in self.event_placements:
                _items.append(_item_event_placements.to_dict() if _item_event_placements is not None else None)
            _dict['event_placements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in roster (list)
        _items = []
        if self.roster:
            for _item_roster in self.roster:
                _items.append(_item_roster.to_dict() if _item_roster is not None else None)
            _dict['roster'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in socials (list)
        _items = []
        if self.socials:
            for _item_socials in self.socials:
                _items.append(_item_socials.to_dict() if _item_socials is not None else None)
            _dict['socials'] = _items
        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if logo (nullable) is None
        # and model_fields_set contains the field
        if self.logo is None and "logo" in self.model_fields_set:
            _dict['logo'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if total_winnings (nullable) is None
        # and model_fields_set contains the field
        if self.total_winnings is None and "total_winnings" in self.model_fields_set:
            _dict['total_winnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsportsV2Team from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country": EsportsV2Country.from_dict(obj["country"]) if obj.get("country") is not None else None,
            "event_placements": [EsportsV2EventPlacement.from_dict(_item) for _item in obj["event_placements"]] if obj.get("event_placements") is not None else None,
            "id": obj.get("id"),
            "logo": obj.get("logo"),
            "name": obj.get("name"),
            "roster": [EsportsV2TeamRosterMember.from_dict(_item) for _item in obj["roster"]] if obj.get("roster") is not None else None,
            "socials": [EsportsV2Social.from_dict(_item) for _item in obj["socials"]] if obj.get("socials") is not None else None,
            "tag": obj.get("tag"),
            "total_winnings": obj.get("total_winnings")
        })
        return _obj


