# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from henrikdev_api_client.models.bundle import Bundle
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeaturedBundle(BaseModel):
    """
    FeaturedBundle
    """ # noqa: E501
    bundle: Bundle = Field(alias="Bundle")
    bundle_remaining_duration_in_seconds: Annotated[int, Field(strict=True, ge=0)] = Field(alias="BundleRemainingDurationInSeconds")
    bundles: List[Bundle] = Field(alias="Bundles")
    __properties: ClassVar[List[str]] = ["Bundle", "BundleRemainingDurationInSeconds", "Bundles"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeaturedBundle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bundle
        if self.bundle:
            _dict['Bundle'] = self.bundle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in bundles (list)
        _items = []
        if self.bundles:
            for _item_bundles in self.bundles:
                _items.append(_item_bundles.to_dict() if _item_bundles is not None else None)
            _dict['Bundles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeaturedBundle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Bundle": Bundle.from_dict(obj["Bundle"]) if obj.get("Bundle") is not None else None,
            "BundleRemainingDurationInSeconds": obj.get("BundleRemainingDurationInSeconds"),
            "Bundles": [Bundle.from_dict(_item) for _item in obj["Bundles"]] if obj.get("Bundles") is not None else None
        })
        return _obj


