# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from henrikdev_api_client.models.matches_v2_data_round_event_location import MatchesV2DataRoundEventLocation
from henrikdev_api_client.models.matches_v2_data_round_player import MatchesV2DataRoundPlayer
from henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event import MatchesV2DataRoundPlayerLocationsOnEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MatchesV2DataRoundPlantEvents(BaseModel):
    """
    MatchesV2DataRoundPlantEvents
    """ # noqa: E501
    plant_location: Optional[MatchesV2DataRoundEventLocation] = None
    plant_site: Optional[StrictStr] = None
    plant_time_in_round: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    planted_by: Optional[MatchesV2DataRoundPlayer] = None
    player_locations_on_plant: Optional[List[MatchesV2DataRoundPlayerLocationsOnEvent]] = None
    __properties: ClassVar[List[str]] = ["plant_location", "plant_site", "plant_time_in_round", "planted_by", "player_locations_on_plant"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchesV2DataRoundPlantEvents from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plant_location
        if self.plant_location:
            _dict['plant_location'] = self.plant_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of planted_by
        if self.planted_by:
            _dict['planted_by'] = self.planted_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in player_locations_on_plant (list)
        _items = []
        if self.player_locations_on_plant:
            for _item_player_locations_on_plant in self.player_locations_on_plant:
                _items.append(_item_player_locations_on_plant.to_dict() if _item_player_locations_on_plant is not None else None)
            _dict['player_locations_on_plant'] = _items
        # set to None if plant_location (nullable) is None
        # and model_fields_set contains the field
        if self.plant_location is None and "plant_location" in self.model_fields_set:
            _dict['plant_location'] = None

        # set to None if plant_site (nullable) is None
        # and model_fields_set contains the field
        if self.plant_site is None and "plant_site" in self.model_fields_set:
            _dict['plant_site'] = None

        # set to None if plant_time_in_round (nullable) is None
        # and model_fields_set contains the field
        if self.plant_time_in_round is None and "plant_time_in_round" in self.model_fields_set:
            _dict['plant_time_in_round'] = None

        # set to None if planted_by (nullable) is None
        # and model_fields_set contains the field
        if self.planted_by is None and "planted_by" in self.model_fields_set:
            _dict['planted_by'] = None

        # set to None if player_locations_on_plant (nullable) is None
        # and model_fields_set contains the field
        if self.player_locations_on_plant is None and "player_locations_on_plant" in self.model_fields_set:
            _dict['player_locations_on_plant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchesV2DataRoundPlantEvents from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plant_location": MatchesV2DataRoundEventLocation.from_dict(obj["plant_location"]) if obj.get("plant_location") is not None else None,
            "plant_site": obj.get("plant_site"),
            "plant_time_in_round": obj.get("plant_time_in_round"),
            "planted_by": MatchesV2DataRoundPlayer.from_dict(obj["planted_by"]) if obj.get("planted_by") is not None else None,
            "player_locations_on_plant": [MatchesV2DataRoundPlayerLocationsOnEvent.from_dict(_item) for _item in obj["player_locations_on_plant"]] if obj.get("player_locations_on_plant") is not None else None
        })
        return _obj


