# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from henrikdev_api_client.models.mmrv3_account import MMRV3Account
from henrikdev_api_client.models.mmrv3_current import MMRV3Current
from henrikdev_api_client.models.mmrv3_peak import MMRV3Peak
from henrikdev_api_client.models.mmrv3_seasonal import MMRV3Seasonal
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MMRV3Data(BaseModel):
    """
    MMRV3Data
    """ # noqa: E501
    account: MMRV3Account
    current: MMRV3Current
    peak: Optional[MMRV3Peak] = None
    seasonal: List[MMRV3Seasonal]
    __properties: ClassVar[List[str]] = ["account", "current", "peak", "seasonal"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MMRV3Data from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current
        if self.current:
            _dict['current'] = self.current.to_dict()
        # override the default output from pydantic by calling `to_dict()` of peak
        if self.peak:
            _dict['peak'] = self.peak.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in seasonal (list)
        _items = []
        if self.seasonal:
            for _item_seasonal in self.seasonal:
                _items.append(_item_seasonal.to_dict() if _item_seasonal is not None else None)
            _dict['seasonal'] = _items
        # set to None if peak (nullable) is None
        # and model_fields_set contains the field
        if self.peak is None and "peak" in self.model_fields_set:
            _dict['peak'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MMRV3Data from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": MMRV3Account.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "current": MMRV3Current.from_dict(obj["current"]) if obj.get("current") is not None else None,
            "peak": MMRV3Peak.from_dict(obj["peak"]) if obj.get("peak") is not None else None,
            "seasonal": [MMRV3Seasonal.from_dict(_item) for _item in obj["seasonal"]] if obj.get("seasonal") is not None else None
        })
        return _obj


