# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from henrikdev_api_client.models.premier_team_games_league_string import PremierTeamGamesLeagueString
from henrikdev_api_client.models.premier_team_games_tournament import PremierTeamGamesTournament
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PremierTeamHistoryV1ResponseData(BaseModel):
    """
    PremierTeamHistoryV1ResponseData
    """ # noqa: E501
    league_matches: List[PremierTeamGamesLeagueString]
    tournament_matches: List[PremierTeamGamesTournament]
    __properties: ClassVar[List[str]] = ["league_matches", "tournament_matches"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PremierTeamHistoryV1ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in league_matches (list)
        _items = []
        if self.league_matches:
            for _item_league_matches in self.league_matches:
                _items.append(_item_league_matches.to_dict() if _item_league_matches is not None else None)
            _dict['league_matches'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tournament_matches (list)
        _items = []
        if self.tournament_matches:
            for _item_tournament_matches in self.tournament_matches:
                _items.append(_item_tournament_matches.to_dict() if _item_tournament_matches is not None else None)
            _dict['tournament_matches'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PremierTeamHistoryV1ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "league_matches": [PremierTeamGamesLeagueString.from_dict(_item) for _item in obj["league_matches"]] if obj.get("league_matches") is not None else None,
            "tournament_matches": [PremierTeamGamesTournament.from_dict(_item) for _item in obj["tournament_matches"]] if obj.get("tournament_matches") is not None else None
        })
        return _obj


