# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from henrikdev_api_client.models.status_incident import StatusIncident
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatusV1Data(BaseModel):
    """
    StatusV1Data
    """ # noqa: E501
    incidents: List[StatusIncident]
    maintenances: List[StatusIncident]
    __properties: ClassVar[List[str]] = ["incidents", "maintenances"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusV1Data from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in incidents (list)
        _items = []
        if self.incidents:
            for _item_incidents in self.incidents:
                _items.append(_item_incidents.to_dict() if _item_incidents is not None else None)
            _dict['incidents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in maintenances (list)
        _items = []
        if self.maintenances:
            for _item_maintenances in self.maintenances:
                _items.append(_item_maintenances.to_dict() if _item_maintenances is not None else None)
            _dict['maintenances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusV1Data from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "incidents": [StatusIncident.from_dict(_item) for _item in obj["incidents"]] if obj.get("incidents") is not None else None,
            "maintenances": [StatusIncident.from_dict(_item) for _item in obj["maintenances"]] if obj.get("maintenances") is not None else None
        })
        return _obj


