# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from henrikdev_api_client.models.store_offers_v1_offer import StoreOffersV1Offer
from henrikdev_api_client.models.store_offers_v1_upgrade_currency import StoreOffersV1UpgradeCurrency
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StoreOffersV1(BaseModel):
    """
    StoreOffersV1
    """ # noqa: E501
    offers: List[StoreOffersV1Offer] = Field(alias="Offers")
    upgrade_currency_offers: List[StoreOffersV1UpgradeCurrency] = Field(alias="UpgradeCurrencyOffers")
    __properties: ClassVar[List[str]] = ["Offers", "UpgradeCurrencyOffers"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoreOffersV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in offers (list)
        _items = []
        if self.offers:
            for _item_offers in self.offers:
                _items.append(_item_offers.to_dict() if _item_offers is not None else None)
            _dict['Offers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in upgrade_currency_offers (list)
        _items = []
        if self.upgrade_currency_offers:
            for _item_upgrade_currency_offers in self.upgrade_currency_offers:
                _items.append(_item_upgrade_currency_offers.to_dict() if _item_upgrade_currency_offers is not None else None)
            _dict['UpgradeCurrencyOffers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoreOffersV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Offers": [StoreOffersV1Offer.from_dict(_item) for _item in obj["Offers"]] if obj.get("Offers") is not None else None,
            "UpgradeCurrencyOffers": [StoreOffersV1UpgradeCurrency.from_dict(_item) for _item in obj["UpgradeCurrencyOffers"]] if obj.get("UpgradeCurrencyOffers") is not None else None
        })
        return _obj


