# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from henrikdev_api_client.models.store_offers_v1_reward import StoreOffersV1Reward
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StoreOffersV1Offer(BaseModel):
    """
    StoreOffersV1Offer
    """ # noqa: E501
    cost: Dict[str, StrictInt] = Field(alias="Cost")
    is_direct_purchase: StrictBool = Field(alias="IsDirectPurchase")
    offer_id: StrictStr = Field(alias="OfferID")
    rewards: List[StoreOffersV1Reward] = Field(alias="Rewards")
    start_date: StrictStr = Field(alias="StartDate")
    __properties: ClassVar[List[str]] = ["Cost", "IsDirectPurchase", "OfferID", "Rewards", "StartDate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoreOffersV1Offer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rewards (list)
        _items = []
        if self.rewards:
            for _item_rewards in self.rewards:
                _items.append(_item_rewards.to_dict() if _item_rewards is not None else None)
            _dict['Rewards'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoreOffersV1Offer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Cost": obj.get("Cost"),
            "IsDirectPurchase": obj.get("IsDirectPurchase"),
            "OfferID": obj.get("OfferID"),
            "Rewards": [StoreOffersV1Reward.from_dict(_item) for _item in obj["Rewards"]] if obj.get("Rewards") is not None else None,
            "StartDate": obj.get("StartDate")
        })
        return _obj


