/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PremiumWebhookUserAddRequest {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::PremiumWebhookEvent>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "puuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<Option<String>>,
    #[serde(rename = "tag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Option<String>>,
}

impl PremiumWebhookUserAddRequest {
    pub fn new() -> PremiumWebhookUserAddRequest {
        PremiumWebhookUserAddRequest {
            enabled: None,
            events: None,
            name: None,
            puuid: None,
            tag: None,
        }
    }
}

