/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PremiumWebhookEvent {
    #[serde(rename = "MATCH")]
    Match,
    #[serde(rename = "MMR")]
    Mmr,

}

impl std::fmt::Display for PremiumWebhookEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Match => write!(f, "MATCH"),
            Self::Mmr => write!(f, "MMR"),
        }
    }
}

impl Default for PremiumWebhookEvent {
    fn default() -> PremiumWebhookEvent {
        Self::Match
    }
}

