/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PremiumWebhookUserUpdateRequest {
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::PremiumWebhookEvent>>,
}

impl PremiumWebhookUserUpdateRequest {
    pub fn new() -> PremiumWebhookUserUpdateRequest {
        PremiumWebhookUserUpdateRequest {
            events: None,
        }
    }
}

