/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PremiumWebhookUserMutationData {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "user")]
    pub user: Box<models::PremiumWebhookUserResponse>,
}

impl PremiumWebhookUserMutationData {
    pub fn new(success: bool, user: models::PremiumWebhookUserResponse) -> PremiumWebhookUserMutationData {
        PremiumWebhookUserMutationData {
            success,
            user: Box::new(user),
        }
    }
}

