/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PremierTeamLiteResponseData {
    #[serde(rename = "affinity")]
    pub affinity: String,
    #[serde(rename = "conference")]
    pub conference: String,
    #[serde(rename = "customization")]
    pub customization: Box<models::PremierTeamV1ResponseDataCustomization>,
    #[serde(rename = "division")]
    pub division: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "losses")]
    pub losses: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ranked")]
    pub ranked: bool,
    #[serde(rename = "ranking")]
    pub ranking: i32,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "wins")]
    pub wins: i32,
}

impl PremierTeamLiteResponseData {
    pub fn new(affinity: String, conference: String, customization: models::PremierTeamV1ResponseDataCustomization, division: i32, id: String, losses: i32, name: String, ranked: bool, ranking: i32, region: String, score: i32, tag: String, updated_at: String, wins: i32) -> PremierTeamLiteResponseData {
        PremierTeamLiteResponseData {
            affinity,
            conference,
            customization: Box::new(customization),
            division,
            id,
            losses,
            name,
            ranked,
            ranking,
            region,
            score,
            tag,
            updated_at,
            wins,
        }
    }
}

