/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PremiumWebhookUserMutationResponse {
    #[serde(rename = "data")]
    pub data: Box<models::PremiumWebhookUserMutationData>,
}

impl PremiumWebhookUserMutationResponse {
    pub fn new(data: models::PremiumWebhookUserMutationData) -> PremiumWebhookUserMutationResponse {
        PremiumWebhookUserMutationResponse {
            data: Box::new(data),
        }
    }
}

