/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremiumWebhookDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookDeleteResponse{}

// PremiumWebhookDeleteResponse struct for PremiumWebhookDeleteResponse
type PremiumWebhookDeleteResponse struct {
	Data PremiumWebhookDeleteData `json:"data"`
}

type _PremiumWebhookDeleteResponse PremiumWebhookDeleteResponse

// NewPremiumWebhookDeleteResponse instantiates a new PremiumWebhookDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookDeleteResponse(data PremiumWebhookDeleteData) *PremiumWebhookDeleteResponse {
	this := PremiumWebhookDeleteResponse{}
	this.Data = data
	return &this
}

// NewPremiumWebhookDeleteResponseWithDefaults instantiates a new PremiumWebhookDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookDeleteResponseWithDefaults() *PremiumWebhookDeleteResponse {
	this := PremiumWebhookDeleteResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PremiumWebhookDeleteResponse) GetData() PremiumWebhookDeleteData {
	if o == nil {
		var ret PremiumWebhookDeleteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookDeleteResponse) GetDataOk() (*PremiumWebhookDeleteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PremiumWebhookDeleteResponse) SetData(v PremiumWebhookDeleteData) {
	o.Data = v
}

func (o PremiumWebhookDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PremiumWebhookDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremiumWebhookDeleteResponse := _PremiumWebhookDeleteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremiumWebhookDeleteResponse)

	if err != nil {
		return err
	}

	*o = PremiumWebhookDeleteResponse(varPremiumWebhookDeleteResponse)

	return err
}

type NullablePremiumWebhookDeleteResponse struct {
	value *PremiumWebhookDeleteResponse
	isSet bool
}

func (v NullablePremiumWebhookDeleteResponse) Get() *PremiumWebhookDeleteResponse {
	return v.value
}

func (v *NullablePremiumWebhookDeleteResponse) Set(val *PremiumWebhookDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookDeleteResponse(val *PremiumWebhookDeleteResponse) *NullablePremiumWebhookDeleteResponse {
	return &NullablePremiumWebhookDeleteResponse{value: val, isSet: true}
}

func (v NullablePremiumWebhookDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


