/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"fmt"
)

// PremiumWebhookEvent the model 'PremiumWebhookEvent'
type PremiumWebhookEvent string

// List of PremiumWebhookEvent
const (
	MATCH PremiumWebhookEvent = "MATCH"
	MMR PremiumWebhookEvent = "MMR"
)

// All allowed values of PremiumWebhookEvent enum
var AllowedPremiumWebhookEventEnumValues = []PremiumWebhookEvent{
	"MATCH",
	"MMR",
}

func (v *PremiumWebhookEvent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PremiumWebhookEvent(value)
	for _, existing := range AllowedPremiumWebhookEventEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PremiumWebhookEvent", value)
}

// NewPremiumWebhookEventFromValue returns a pointer to a valid PremiumWebhookEvent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPremiumWebhookEventFromValue(v string) (*PremiumWebhookEvent, error) {
	ev := PremiumWebhookEvent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PremiumWebhookEvent: valid values are %v", v, AllowedPremiumWebhookEventEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PremiumWebhookEvent) IsValid() bool {
	for _, existing := range AllowedPremiumWebhookEventEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PremiumWebhookEvent value
func (v PremiumWebhookEvent) Ptr() *PremiumWebhookEvent {
	return &v
}

type NullablePremiumWebhookEvent struct {
	value *PremiumWebhookEvent
	isSet bool
}

func (v NullablePremiumWebhookEvent) Get() *PremiumWebhookEvent {
	return v.value
}

func (v *NullablePremiumWebhookEvent) Set(val *PremiumWebhookEvent) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookEvent) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookEvent(val *PremiumWebhookEvent) *NullablePremiumWebhookEvent {
	return &NullablePremiumWebhookEvent{value: val, isSet: true}
}

func (v NullablePremiumWebhookEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

