/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremiumWebhookUserMutationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookUserMutationResponse{}

// PremiumWebhookUserMutationResponse struct for PremiumWebhookUserMutationResponse
type PremiumWebhookUserMutationResponse struct {
	Data PremiumWebhookUserMutationData `json:"data"`
}

type _PremiumWebhookUserMutationResponse PremiumWebhookUserMutationResponse

// NewPremiumWebhookUserMutationResponse instantiates a new PremiumWebhookUserMutationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookUserMutationResponse(data PremiumWebhookUserMutationData) *PremiumWebhookUserMutationResponse {
	this := PremiumWebhookUserMutationResponse{}
	this.Data = data
	return &this
}

// NewPremiumWebhookUserMutationResponseWithDefaults instantiates a new PremiumWebhookUserMutationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookUserMutationResponseWithDefaults() *PremiumWebhookUserMutationResponse {
	this := PremiumWebhookUserMutationResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PremiumWebhookUserMutationResponse) GetData() PremiumWebhookUserMutationData {
	if o == nil {
		var ret PremiumWebhookUserMutationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserMutationResponse) GetDataOk() (*PremiumWebhookUserMutationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PremiumWebhookUserMutationResponse) SetData(v PremiumWebhookUserMutationData) {
	o.Data = v
}

func (o PremiumWebhookUserMutationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookUserMutationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PremiumWebhookUserMutationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremiumWebhookUserMutationResponse := _PremiumWebhookUserMutationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremiumWebhookUserMutationResponse)

	if err != nil {
		return err
	}

	*o = PremiumWebhookUserMutationResponse(varPremiumWebhookUserMutationResponse)

	return err
}

type NullablePremiumWebhookUserMutationResponse struct {
	value *PremiumWebhookUserMutationResponse
	isSet bool
}

func (v NullablePremiumWebhookUserMutationResponse) Get() *PremiumWebhookUserMutationResponse {
	return v.value
}

func (v *NullablePremiumWebhookUserMutationResponse) Set(val *PremiumWebhookUserMutationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookUserMutationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookUserMutationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookUserMutationResponse(val *PremiumWebhookUserMutationResponse) *NullablePremiumWebhookUserMutationResponse {
	return &NullablePremiumWebhookUserMutationResponse{value: val, isSet: true}
}

func (v NullablePremiumWebhookUserMutationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookUserMutationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


