/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremiumWebhookDeleteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookDeleteData{}

// PremiumWebhookDeleteData struct for PremiumWebhookDeleteData
type PremiumWebhookDeleteData struct {
	Deleted bool `json:"deleted"`
}

type _PremiumWebhookDeleteData PremiumWebhookDeleteData

// NewPremiumWebhookDeleteData instantiates a new PremiumWebhookDeleteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookDeleteData(deleted bool) *PremiumWebhookDeleteData {
	this := PremiumWebhookDeleteData{}
	this.Deleted = deleted
	return &this
}

// NewPremiumWebhookDeleteDataWithDefaults instantiates a new PremiumWebhookDeleteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookDeleteDataWithDefaults() *PremiumWebhookDeleteData {
	this := PremiumWebhookDeleteData{}
	return &this
}

// GetDeleted returns the Deleted field value
func (o *PremiumWebhookDeleteData) GetDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookDeleteData) GetDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deleted, true
}

// SetDeleted sets field value
func (o *PremiumWebhookDeleteData) SetDeleted(v bool) {
	o.Deleted = v
}

func (o PremiumWebhookDeleteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookDeleteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deleted"] = o.Deleted
	return toSerialize, nil
}

func (o *PremiumWebhookDeleteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremiumWebhookDeleteData := _PremiumWebhookDeleteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremiumWebhookDeleteData)

	if err != nil {
		return err
	}

	*o = PremiumWebhookDeleteData(varPremiumWebhookDeleteData)

	return err
}

type NullablePremiumWebhookDeleteData struct {
	value *PremiumWebhookDeleteData
	isSet bool
}

func (v NullablePremiumWebhookDeleteData) Get() *PremiumWebhookDeleteData {
	return v.value
}

func (v *NullablePremiumWebhookDeleteData) Set(val *PremiumWebhookDeleteData) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookDeleteData) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookDeleteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookDeleteData(val *PremiumWebhookDeleteData) *NullablePremiumWebhookDeleteData {
	return &NullablePremiumWebhookDeleteData{value: val, isSet: true}
}

func (v NullablePremiumWebhookDeleteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookDeleteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


