/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremiumWebhookUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookUserResponse{}

// PremiumWebhookUserResponse struct for PremiumWebhookUserResponse
type PremiumWebhookUserResponse struct {
	CreatedAt int64 `json:"created_at"`
	Enabled bool `json:"enabled"`
	Events []PremiumWebhookEvent `json:"events"`
	Id string `json:"id"`
	LastCheckedAt NullableInt64 `json:"last_checked_at,omitempty"`
	LastMatch NullableString `json:"last_match,omitempty"`
	LastMmr NullableInt32 `json:"last_mmr,omitempty"`
	Puuid string `json:"puuid"`
	Region string `json:"region"`
	UpdatedAt int64 `json:"updated_at"`
}

type _PremiumWebhookUserResponse PremiumWebhookUserResponse

// NewPremiumWebhookUserResponse instantiates a new PremiumWebhookUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookUserResponse(createdAt int64, enabled bool, events []PremiumWebhookEvent, id string, puuid string, region string, updatedAt int64) *PremiumWebhookUserResponse {
	this := PremiumWebhookUserResponse{}
	this.CreatedAt = createdAt
	this.Enabled = enabled
	this.Events = events
	this.Id = id
	this.Puuid = puuid
	this.Region = region
	this.UpdatedAt = updatedAt
	return &this
}

// NewPremiumWebhookUserResponseWithDefaults instantiates a new PremiumWebhookUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookUserResponseWithDefaults() *PremiumWebhookUserResponse {
	this := PremiumWebhookUserResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *PremiumWebhookUserResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PremiumWebhookUserResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetEnabled returns the Enabled field value
func (o *PremiumWebhookUserResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *PremiumWebhookUserResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEvents returns the Events field value
func (o *PremiumWebhookUserResponse) GetEvents() []PremiumWebhookEvent {
	if o == nil {
		var ret []PremiumWebhookEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetEventsOk() ([]PremiumWebhookEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *PremiumWebhookUserResponse) SetEvents(v []PremiumWebhookEvent) {
	o.Events = v
}

// GetId returns the Id field value
func (o *PremiumWebhookUserResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PremiumWebhookUserResponse) SetId(v string) {
	o.Id = v
}

// GetLastCheckedAt returns the LastCheckedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserResponse) GetLastCheckedAt() int64 {
	if o == nil || IsNil(o.LastCheckedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.LastCheckedAt.Get()
}

// GetLastCheckedAtOk returns a tuple with the LastCheckedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserResponse) GetLastCheckedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastCheckedAt.Get(), o.LastCheckedAt.IsSet()
}

// HasLastCheckedAt returns a boolean if a field has been set.
func (o *PremiumWebhookUserResponse) HasLastCheckedAt() bool {
	if o != nil && o.LastCheckedAt.IsSet() {
		return true
	}

	return false
}

// SetLastCheckedAt gets a reference to the given NullableInt64 and assigns it to the LastCheckedAt field.
func (o *PremiumWebhookUserResponse) SetLastCheckedAt(v int64) {
	o.LastCheckedAt.Set(&v)
}
// SetLastCheckedAtNil sets the value for LastCheckedAt to be an explicit nil
func (o *PremiumWebhookUserResponse) SetLastCheckedAtNil() {
	o.LastCheckedAt.Set(nil)
}

// UnsetLastCheckedAt ensures that no value is present for LastCheckedAt, not even an explicit nil
func (o *PremiumWebhookUserResponse) UnsetLastCheckedAt() {
	o.LastCheckedAt.Unset()
}

// GetLastMatch returns the LastMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserResponse) GetLastMatch() string {
	if o == nil || IsNil(o.LastMatch.Get()) {
		var ret string
		return ret
	}
	return *o.LastMatch.Get()
}

// GetLastMatchOk returns a tuple with the LastMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserResponse) GetLastMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastMatch.Get(), o.LastMatch.IsSet()
}

// HasLastMatch returns a boolean if a field has been set.
func (o *PremiumWebhookUserResponse) HasLastMatch() bool {
	if o != nil && o.LastMatch.IsSet() {
		return true
	}

	return false
}

// SetLastMatch gets a reference to the given NullableString and assigns it to the LastMatch field.
func (o *PremiumWebhookUserResponse) SetLastMatch(v string) {
	o.LastMatch.Set(&v)
}
// SetLastMatchNil sets the value for LastMatch to be an explicit nil
func (o *PremiumWebhookUserResponse) SetLastMatchNil() {
	o.LastMatch.Set(nil)
}

// UnsetLastMatch ensures that no value is present for LastMatch, not even an explicit nil
func (o *PremiumWebhookUserResponse) UnsetLastMatch() {
	o.LastMatch.Unset()
}

// GetLastMmr returns the LastMmr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserResponse) GetLastMmr() int32 {
	if o == nil || IsNil(o.LastMmr.Get()) {
		var ret int32
		return ret
	}
	return *o.LastMmr.Get()
}

// GetLastMmrOk returns a tuple with the LastMmr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserResponse) GetLastMmrOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastMmr.Get(), o.LastMmr.IsSet()
}

// HasLastMmr returns a boolean if a field has been set.
func (o *PremiumWebhookUserResponse) HasLastMmr() bool {
	if o != nil && o.LastMmr.IsSet() {
		return true
	}

	return false
}

// SetLastMmr gets a reference to the given NullableInt32 and assigns it to the LastMmr field.
func (o *PremiumWebhookUserResponse) SetLastMmr(v int32) {
	o.LastMmr.Set(&v)
}
// SetLastMmrNil sets the value for LastMmr to be an explicit nil
func (o *PremiumWebhookUserResponse) SetLastMmrNil() {
	o.LastMmr.Set(nil)
}

// UnsetLastMmr ensures that no value is present for LastMmr, not even an explicit nil
func (o *PremiumWebhookUserResponse) UnsetLastMmr() {
	o.LastMmr.Unset()
}

// GetPuuid returns the Puuid field value
func (o *PremiumWebhookUserResponse) GetPuuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Puuid
}

// GetPuuidOk returns a tuple with the Puuid field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetPuuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Puuid, true
}

// SetPuuid sets field value
func (o *PremiumWebhookUserResponse) SetPuuid(v string) {
	o.Puuid = v
}

// GetRegion returns the Region field value
func (o *PremiumWebhookUserResponse) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *PremiumWebhookUserResponse) SetRegion(v string) {
	o.Region = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PremiumWebhookUserResponse) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserResponse) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PremiumWebhookUserResponse) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

func (o PremiumWebhookUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["enabled"] = o.Enabled
	toSerialize["events"] = o.Events
	toSerialize["id"] = o.Id
	if o.LastCheckedAt.IsSet() {
		toSerialize["last_checked_at"] = o.LastCheckedAt.Get()
	}
	if o.LastMatch.IsSet() {
		toSerialize["last_match"] = o.LastMatch.Get()
	}
	if o.LastMmr.IsSet() {
		toSerialize["last_mmr"] = o.LastMmr.Get()
	}
	toSerialize["puuid"] = o.Puuid
	toSerialize["region"] = o.Region
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *PremiumWebhookUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"enabled",
		"events",
		"id",
		"puuid",
		"region",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremiumWebhookUserResponse := _PremiumWebhookUserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremiumWebhookUserResponse)

	if err != nil {
		return err
	}

	*o = PremiumWebhookUserResponse(varPremiumWebhookUserResponse)

	return err
}

type NullablePremiumWebhookUserResponse struct {
	value *PremiumWebhookUserResponse
	isSet bool
}

func (v NullablePremiumWebhookUserResponse) Get() *PremiumWebhookUserResponse {
	return v.value
}

func (v *NullablePremiumWebhookUserResponse) Set(val *PremiumWebhookUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookUserResponse(val *PremiumWebhookUserResponse) *NullablePremiumWebhookUserResponse {
	return &NullablePremiumWebhookUserResponse{value: val, isSet: true}
}

func (v NullablePremiumWebhookUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


