/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremiumWebhookUserMutationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookUserMutationData{}

// PremiumWebhookUserMutationData struct for PremiumWebhookUserMutationData
type PremiumWebhookUserMutationData struct {
	Success bool `json:"success"`
	User PremiumWebhookUserResponse `json:"user"`
}

type _PremiumWebhookUserMutationData PremiumWebhookUserMutationData

// NewPremiumWebhookUserMutationData instantiates a new PremiumWebhookUserMutationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookUserMutationData(success bool, user PremiumWebhookUserResponse) *PremiumWebhookUserMutationData {
	this := PremiumWebhookUserMutationData{}
	this.Success = success
	this.User = user
	return &this
}

// NewPremiumWebhookUserMutationDataWithDefaults instantiates a new PremiumWebhookUserMutationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookUserMutationDataWithDefaults() *PremiumWebhookUserMutationData {
	this := PremiumWebhookUserMutationData{}
	return &this
}

// GetSuccess returns the Success field value
func (o *PremiumWebhookUserMutationData) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserMutationData) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *PremiumWebhookUserMutationData) SetSuccess(v bool) {
	o.Success = v
}

// GetUser returns the User field value
func (o *PremiumWebhookUserMutationData) GetUser() PremiumWebhookUserResponse {
	if o == nil {
		var ret PremiumWebhookUserResponse
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserMutationData) GetUserOk() (*PremiumWebhookUserResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *PremiumWebhookUserMutationData) SetUser(v PremiumWebhookUserResponse) {
	o.User = v
}

func (o PremiumWebhookUserMutationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookUserMutationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *PremiumWebhookUserMutationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremiumWebhookUserMutationData := _PremiumWebhookUserMutationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremiumWebhookUserMutationData)

	if err != nil {
		return err
	}

	*o = PremiumWebhookUserMutationData(varPremiumWebhookUserMutationData)

	return err
}

type NullablePremiumWebhookUserMutationData struct {
	value *PremiumWebhookUserMutationData
	isSet bool
}

func (v NullablePremiumWebhookUserMutationData) Get() *PremiumWebhookUserMutationData {
	return v.value
}

func (v *NullablePremiumWebhookUserMutationData) Set(val *PremiumWebhookUserMutationData) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookUserMutationData) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookUserMutationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookUserMutationData(val *PremiumWebhookUserMutationData) *NullablePremiumWebhookUserMutationData {
	return &NullablePremiumWebhookUserMutationData{value: val, isSet: true}
}

func (v NullablePremiumWebhookUserMutationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookUserMutationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


