/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
)

// checks if the PremiumWebhookUserAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremiumWebhookUserAddRequest{}

// PremiumWebhookUserAddRequest struct for PremiumWebhookUserAddRequest
type PremiumWebhookUserAddRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
	Events []PremiumWebhookEvent `json:"events,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Puuid NullableString `json:"puuid,omitempty"`
	Tag NullableString `json:"tag,omitempty"`
}

// NewPremiumWebhookUserAddRequest instantiates a new PremiumWebhookUserAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremiumWebhookUserAddRequest() *PremiumWebhookUserAddRequest {
	this := PremiumWebhookUserAddRequest{}
	return &this
}

// NewPremiumWebhookUserAddRequestWithDefaults instantiates a new PremiumWebhookUserAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremiumWebhookUserAddRequestWithDefaults() *PremiumWebhookUserAddRequest {
	this := PremiumWebhookUserAddRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PremiumWebhookUserAddRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserAddRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PremiumWebhookUserAddRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PremiumWebhookUserAddRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *PremiumWebhookUserAddRequest) GetEvents() []PremiumWebhookEvent {
	if o == nil || IsNil(o.Events) {
		var ret []PremiumWebhookEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PremiumWebhookUserAddRequest) GetEventsOk() ([]PremiumWebhookEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *PremiumWebhookUserAddRequest) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []PremiumWebhookEvent and assigns it to the Events field.
func (o *PremiumWebhookUserAddRequest) SetEvents(v []PremiumWebhookEvent) {
	o.Events = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserAddRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserAddRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PremiumWebhookUserAddRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PremiumWebhookUserAddRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *PremiumWebhookUserAddRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PremiumWebhookUserAddRequest) UnsetName() {
	o.Name.Unset()
}

// GetPuuid returns the Puuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserAddRequest) GetPuuid() string {
	if o == nil || IsNil(o.Puuid.Get()) {
		var ret string
		return ret
	}
	return *o.Puuid.Get()
}

// GetPuuidOk returns a tuple with the Puuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserAddRequest) GetPuuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Puuid.Get(), o.Puuid.IsSet()
}

// HasPuuid returns a boolean if a field has been set.
func (o *PremiumWebhookUserAddRequest) HasPuuid() bool {
	if o != nil && o.Puuid.IsSet() {
		return true
	}

	return false
}

// SetPuuid gets a reference to the given NullableString and assigns it to the Puuid field.
func (o *PremiumWebhookUserAddRequest) SetPuuid(v string) {
	o.Puuid.Set(&v)
}
// SetPuuidNil sets the value for Puuid to be an explicit nil
func (o *PremiumWebhookUserAddRequest) SetPuuidNil() {
	o.Puuid.Set(nil)
}

// UnsetPuuid ensures that no value is present for Puuid, not even an explicit nil
func (o *PremiumWebhookUserAddRequest) UnsetPuuid() {
	o.Puuid.Unset()
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PremiumWebhookUserAddRequest) GetTag() string {
	if o == nil || IsNil(o.Tag.Get()) {
		var ret string
		return ret
	}
	return *o.Tag.Get()
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PremiumWebhookUserAddRequest) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tag.Get(), o.Tag.IsSet()
}

// HasTag returns a boolean if a field has been set.
func (o *PremiumWebhookUserAddRequest) HasTag() bool {
	if o != nil && o.Tag.IsSet() {
		return true
	}

	return false
}

// SetTag gets a reference to the given NullableString and assigns it to the Tag field.
func (o *PremiumWebhookUserAddRequest) SetTag(v string) {
	o.Tag.Set(&v)
}
// SetTagNil sets the value for Tag to be an explicit nil
func (o *PremiumWebhookUserAddRequest) SetTagNil() {
	o.Tag.Set(nil)
}

// UnsetTag ensures that no value is present for Tag, not even an explicit nil
func (o *PremiumWebhookUserAddRequest) UnsetTag() {
	o.Tag.Unset()
}

func (o PremiumWebhookUserAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremiumWebhookUserAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Puuid.IsSet() {
		toSerialize["puuid"] = o.Puuid.Get()
	}
	if o.Tag.IsSet() {
		toSerialize["tag"] = o.Tag.Get()
	}
	return toSerialize, nil
}

type NullablePremiumWebhookUserAddRequest struct {
	value *PremiumWebhookUserAddRequest
	isSet bool
}

func (v NullablePremiumWebhookUserAddRequest) Get() *PremiumWebhookUserAddRequest {
	return v.value
}

func (v *NullablePremiumWebhookUserAddRequest) Set(val *PremiumWebhookUserAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePremiumWebhookUserAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePremiumWebhookUserAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremiumWebhookUserAddRequest(val *PremiumWebhookUserAddRequest) *NullablePremiumWebhookUserAddRequest {
	return &NullablePremiumWebhookUserAddRequest{value: val, isSet: true}
}

func (v NullablePremiumWebhookUserAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremiumWebhookUserAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


