/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.PremiumWebhookEvent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled 
 * @param events 
 * @param name 
 * @param puuid 
 * @param tag 
 */


data class PremiumWebhookUserAddRequest (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "events")
    val events: kotlin.collections.List<PremiumWebhookEvent>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "puuid")
    val puuid: kotlin.String? = null,

    @Json(name = "tag")
    val tag: kotlin.String? = null

) {


}

